#!/usr/bin/env bash
# author: joe.zheng
# version: 23.12.03

set -e

SELF="$(basename $0)"
SELF_VERSION="$(sed -n '1,4s/# version: \(.*\)/\1/p' $0)"
NAME="${SELF#*-}"

SUDO="sudo"
if [[ $(id -u) == "0" ]]; then
  SUDO=""
fi

VERSION="1.12.6"      # version to deploy
DRY_RUN=n             # print information only
MIRROR="auto"         # mirror option
MIRRORS="yes no auto" # valid mirror options
RESET=n               # reset the deployment
UNINSTALL=n           # reset the deployment and uninstall components
OFFLINE=${OFFLINE:-n} # no external network

REPO_URL="https://github.com/cert-manager/cert-manager"
MIRROR_URL="${MIRROR_URL:-https://ghps.cc}"
GCLOUD_URL="https://packages.cloud.google.com"

VARIANT="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/')"
TIMEOUT="300s"
NAMESPACE="$NAME"

CACHE="cache"
CACHE_MANIFESTS="$CACHE/manifests"
CACHE_PACKAGES="$CACHE/packages/common"
CACHE_RUN="$CACHE/run/$SELF"

function msg() {
  echo "> $@"
}

function err() {
  echo "> $@" >&2
}

function usage() {
  cat <<EOF
Usage: $SELF [-m <type>] [-v <ver>] [-R] [-U] [-n] [-h]

  Deploy $NAME in Kubernetes cluster the easy way

  -m <type>: use mirror [$MIRRORS], default: $MIRROR
  -v <ver>:  target version, default: $VERSION
  -R:        reset the deployment, default: $RESET
  -U:        reset the deployment and uninstall components, default: $UNINSTALL
  -n:        print information only, default: $DRY_RUN
  -h:        print the usage message

Cache:

  To speed up deployment, the required files will be cached at "$CACHE"

Environment variables:
  MIRROR_URL:  mirror to use, default: $MIRROR_URL
  OFFLINE:     force into offline mode [y n], default: $OFFLINE

Examples:

  1. Deploy $NAME
     $SELF

  2. Reset the deployment
     $SELF -R

  3. Deploy $NAME with specific version
     $SELF -v $VERSION

  4. Reset the deployment and uninstall
     $SELF -U

Version: $SELF_VERSION
EOF

}

function current_version() {
  local version=
  if which cmctl >/dev/null; then
    version="$(cmctl version --short 2>/dev/null | sed -n 's/Server Version: v\(.*\)/\1/p')"
  fi
  echo $version
}

function validate_sudo() {
  if [[ -n $SUDO ]]; then
    msg "validate sudo"
    sudo -v
  fi
}

function main() {
  # adjust default version if already deployed
  local deployed="$(current_version)"
  VERSION="${deployed:-$VERSION}"

  while getopts ":m:v:hnRU" opt
  do
    case $opt in
      m ) MIRROR=$OPTARG
          if echo $MIRRORS | grep -v -w $MIRROR >/dev/null 2>&1; then
            err "invalid mirror option $MIRROR"
            usage && exit 1
          fi
          ;;
      v ) VERSION=${OPTARG#v};;
      R ) RESET=y;;
      U ) RESET=y && UNINSTALL=y;;
      n ) DRY_RUN=y;;
      h ) usage && exit;;
      * ) usage && echo "invalid option: -$OPTARG" && exit 1;;
    esac
  done
  shift $((OPTIND-1))

  for v in CACHE DRY_RUN MIRROR MIRROR_URL OFFLINE RESET UNINSTALL VERSION
  do
    eval echo "$v: \${$v}"
  done

  msg "deployed version: $deployed"

  [[ $DRY_RUN == "y" ]] && exit

  validate_sudo
  check_prerequisites
  check_network
  check_mirror
  ensure_workdir

  local manifest_dir="$CACHE_MANIFESTS/$NAME-$VERSION"
  local manifest_list="cert-manager.yaml"
  local package_dir="$CACHE_PACKAGES/$NAME-$VERSION"
  local package_list="cmctl"
  local install_dir="/usr/local/bin"

  mkdir -p $package_dir $manifest_dir

  local base_url="$REPO_URL"
  if [[ $NEED_MIRROR == "y" ]]; then
    base_url="$MIRROR_URL/$REPO_URL"
  fi

  msg "download manifests"
  for n in $manifest_list; do
    local f="$manifest_dir/$n"
    if [[ ! -e "$f" ]]; then
      if [[ $OFFLINE == "y" ]]; then
        err "no cache found: $f"
        exit 1
      fi
      local u="$base_url/releases/download/v$VERSION/$n"
      msg "download $u -> $f"
      curl -L $u > $f
    fi
  done

  msg "download packages"
  for n in $package_list; do
    local f="$package_dir/$n"
    msg "check $f"
    if [[ ! -e "$f" ]]; then
      if [[ $OFFLINE == "y" ]]; then
        err "no cache found: $f"
        exit 1
      fi
      local u="$base_url/releases/download/v$VERSION/$n-$VARIANT.tar.gz"
      msg "download $u -> $f"
      curl -L $u | tar xz -C $package_dir $n
    fi
  done

  if [[ $RESET == "y" ]]; then
    local kd="kubectl delete --ignore-not-found"
    if [[ -n "$deployed" ]]; then
      msg "clean it up first"
      $kd -A --all issuer,clusterissuer,certificate,certificaterequest,order,challenge
    fi
    msg "delete $NAME deployment (if any)"
    for m in "$manifest_list"; do
      $kd -f "$manifest_dir/$m"
    done
  else
    msg "deploy $NAME"
    for m in "$manifest_list"; do
      kubectl apply -f "$manifest_dir/$m"
    done
  fi

  if [[ $UNINSTALL == "y" ]]; then
    msg "uninstall $package_list"
    for n in "$package_list"; do
      $SUDO rm -f $install_dir/$n
    done
  else
    msg "install $package_list"
    for n in "$package_list"; do
      $SUDO install -t $install_dir $package_dir/$n
    done
  fi

  if [[ $RESET != "y" ]]; then
    msg "wait until ready (timeout: $TIMEOUT)"
    cmctl check api --wait=$TIMEOUT

cat <<EOF > $CACHE_RUN/test-selfsigned.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
EOF

    cat <<EOF

# here are some tips to follow:
# check current status
kubectl get all -n $NAMESPACE

# check client and server version
cmctl version

# create a self-signed issuer and a certificate for test
kubectl apply -f $CACHE_RUN/test-selfsigned.yaml

# list all the issuers and certificates
kubectl get issuer,certificate -A

# check more details from $REPO_URL
EOF
  fi

  msg "done"
}

function check_prerequisites() {
  msg "check prerequisites"
  if [[ -z $(which kubelet) ]]; then
    err "kubelet is not available"
    exit 1
  fi
  if [[ -z $(which curl) ]]; then
    err "curl is not available"
    exit 1
  fi
  if ! kubectl version >/dev/null 2>&1; then
    err "can't access k8s cluster"
    exit 1
  fi
}

function check_network() {
  msg "check network"
  if [[ $OFFLINE != 'y' ]]; then
    if ! curl -s -m 3 -I example.com >/dev/null; then
      msg "can't access external network"
      OFFLINE="y"
    fi
  fi
  msg "offline mode: $OFFLINE"
}

NEED_MIRROR=n
function check_mirror() {
  msg "is mirror needed"
  if [[ $MIRROR == "auto" ]]; then
    MIRROR=yes # default as needed
    if [[ $OFFLINE == "y" ]]; then
      msg "offline mode, assume mirror is needed"
    else
      msg "check whether we can access google cloud"
      local target="$GCLOUD_URL"
      if curl -s -m 5 $target >/dev/null 2>&1; then
        msg "curl $target is OK"
        MIRROR=no
      else
        msg "curl $target is FAILED"
      fi
    fi
  fi
  if [[ $MIRROR == "yes" ]]; then
    NEED_MIRROR=y
  fi
  msg "need mirror: $NEED_MIRROR"
}

function ensure_workdir() {
  msg "ensure workdir"

  for d in $CACHE_MANIFESTS $CACHE_PACKAGES $CACHE_RUN; do
    if [[ ! -d $d ]]; then
      msg "create dir: $d"
      mkdir -p $d
    fi
  done
}

main "$@"
