#!/usr/bin/env bash
# author: joe.zheng
# version: 23.12.07

set -e

SELF="$(basename $0)"
SELF_VERSION="$(sed -n '1,4s/# version: \(.*\)/\1/p' $0)"
NAME="${SELF#*-}"

VERSION="0.13.12"     # version to deploy
DRY_RUN=n             # print information only
MIRROR="auto"         # mirror option
MIRRORS="yes no auto" # valid mirror options
RESET=n               # reset the deployment
UNINSTALL=n           # reset the deployment and uninstall components
OFFLINE=${OFFLINE:-n} # no external network

REPO_URL="https://github.com/metallb/metallb"
MIRROR_URL="${MIRROR_URL:-https://iffi.me/proxy}"
GCLOUD_URL="https://packages.cloud.google.com"

TIMEOUT="300s"
NAMESPACE="metallb-system"

CACHE="cache"
CACHE_MANIFESTS="$CACHE/manifests"
CACHE_PACKAGES="$CACHE/packages/common"
CACHE_RUN="$CACHE/run/$SELF"

function msg() {
  echo "> $@"
}

function err() {
  echo "> $@" >&2
}

function usage() {
  cat <<EOF
Usage: $SELF [-m <type>] [-v <ver>] [-R] [-U] [-n] [-h]

  Deploy MetalLB in Kubernetes cluster the easy way

  -m <type>: use mirror [$MIRRORS], default: $MIRROR
  -v <ver>:  target version, default: $VERSION
  -R:        reset the deployment, default: $RESET
  -U:        reset the deployment and uninstall components, default: $UNINSTALL
  -n:        print information only, default: $DRY_RUN
  -h:        print the usage message

Cache:

  To speed up deployment, the required files will be cached at "$CACHE"

Environment variables:
  MIRROR_URL:  mirror to use, default: $MIRROR_URL
  OFFLINE:     force into offline mode [y n], default: $OFFLINE

Examples:

  1. Deploy MetalLB
     $SELF

  2. Reset the deployment
     $SELF -R

  3. Deploy MetalLB with specific version
     $SELF -v $VERSION

  4. Reset the deployment and uninstall
     $SELF -U

Version: $SELF_VERSION
EOF

}

function current_version() {
  local version=
  if which kubectl >/dev/null; then
    version="$(kubectl describe -n $NAMESPACE deploy/controller 2>/dev/null | sed -n 's/^\s*Image:\s*.*://p')"
    version="${version#v}"
  fi
  echo $version
}

function main() {
  # adjust default version if already deployed
  local deployed="$(current_version)"
  VERSION="${deployed:-$VERSION}"

  while getopts ":m:v:hnRU" opt
  do
    case $opt in
      m ) MIRROR=$OPTARG
          if echo $MIRRORS | grep -v -w $MIRROR >/dev/null 2>&1; then
            err "invalid mirror option $MIRROR"
            usage && exit 1
          fi
          ;;
      v ) VERSION=${OPTARG#v};;
      R ) RESET=y;;
      U ) RESET=y && UNINSTALL=y;;
      n ) DRY_RUN=y;;
      h ) usage && exit;;
      * ) usage && echo "invalid option: -$OPTARG" && exit 1;;
    esac
  done
  shift $((OPTIND-1))

  for v in CACHE DRY_RUN MIRROR MIRROR_URL OFFLINE RESET UNINSTALL VERSION
  do
    eval echo "$v: \${$v}"
  done

  msg "deployed version: $deployed"

  [[ $DRY_RUN == "y" ]] && exit

  check_prerequisites
  check_network
  check_mirror
  ensure_workdir

  local manifest_dir="$CACHE_MANIFESTS/$NAME-$VERSION"
  local manifest_list="
    metallb-frr.yaml
    metallb-frr-prometheus.yaml
    metallb-native.yaml
    metallb-native-prometheus.yaml
    "

  mkdir -p $manifest_dir

  local base_url="$REPO_URL"
  if [[ $NEED_MIRROR == "y" ]]; then
    base_url="$MIRROR_URL/$REPO_URL"
  fi

  msg "download manifests"
  for m in $manifest_list; do
    local u="$base_url/raw/v$VERSION/config/manifests/$m"
    local f="$manifest_dir/$m"
    if [[ ! -e "$f" ]]; then
      if [[ $OFFLINE == "y" ]]; then
        err "no cache found: $package_path"
        exit 1
      else
        msg "download $u -> $f"
        curl -L $u > $f
      fi
    fi
  done

  if [[ $RESET == "y" ]]; then
    msg "delete $NAME deployment (if any)"
    kubectl delete --ignore-not-found -f "$manifest_dir/metallb-native.yaml" || true
  else
    msg "deploy $NAME"
    kubectl apply -f "$manifest_dir/metallb-native.yaml"
  fi

  if [[ $RESET != "y" ]]; then
    msg "wait until ready (timeout: $TIMEOUT)"
    kubectl -n $NAMESPACE wait deploy/controller --timeout $TIMEOUT --for condition=Available


cat <<EOF > $CACHE_RUN/test-l2.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: test-lb-l2
  namespace: metallb-system
EOF

    cat <<EOF

# here are some tips to follow:
# check current status
kubectl get all -n $NAMESPACE

# configure metallb in L2 mode and define IP pool
# you need to adjust the IP address range first
kubectl apply -f $CACHE_RUN/test-l2.yaml

# create a test service with type LoadBalancer
kubectl create deployment nginx --image=nginx
kubectl expose deployment nginx --type=LoadBalancer --name=nginx --port=80 --protocol=TCP
kubectl get svc nginx -w

# check more details from $REPO_URL
EOF
  fi

  msg "done"
}

function check_prerequisites() {
  msg "check prerequisites"
  if [[ -z $(which kubelet) ]]; then
    err "kubelet is not available"
    exit 1
  fi
  if [[ -z $(which curl) ]]; then
    err "curl is not available"
    exit 1
  fi
  if ! kubectl version >/dev/null 2>&1; then
    err "can't access k8s cluster"
    exit 1
  fi
}

function check_network() {
  msg "check network"
  if [[ $OFFLINE != 'y' ]]; then
    if ! curl -s -m 3 -I example.com >/dev/null; then
      msg "can't access external network"
      OFFLINE="y"
    fi
  fi
  msg "offline mode: $OFFLINE"
}

NEED_MIRROR=n
function check_mirror() {
  msg "is mirror needed"
  if [[ $MIRROR == "auto" ]]; then
    MIRROR=yes # default as needed
    if [[ $OFFLINE == "y" ]]; then
      msg "offline mode, assume mirror is needed"
    else
      msg "check whether we can access google cloud"
      local target="$GCLOUD_URL"
      if curl -s -m 5 $target >/dev/null 2>&1; then
        msg "curl $target is OK"
        MIRROR=no
      else
        msg "curl $target is FAILED"
      fi
    fi
  fi
  if [[ $MIRROR == "yes" ]]; then
    NEED_MIRROR=y
  fi
  msg "need mirror: $NEED_MIRROR"
}

function ensure_workdir() {
  msg "ensure workdir"

  for d in $CACHE_MANIFESTS $CACHE_PACKAGES $CACHE_RUN; do
    if [[ ! -d $d ]]; then
      msg "create dir: $d"
      mkdir -p $d
    fi
  done
}

main "$@"
