#!/usr/bin/env bash
# author: joe.zheng
# version: 23.04.14

set -e

SELF="$(basename $0)"
HOST_NAME="$(cat /proc/sys/kernel/hostname)"

SUDO="sudo"
if [[ $(id -u) == "0" ]]; then
  SUDO=""
fi

PROXY_HOST=""
PROXY_PORT=""
PROXY_SKIP="localhost,$HOSTNAME,istio-system.svc,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.0.0.0/8"
PORT_HTTP="912"
PORT_HTTPS="912"
REPO_MIRROR="https://hub-mirror.c.163.com"
MIRROR=auto           # mirror option
MIRRORS="yes no auto" # valid mirror options

DRY_RUN="n"

HELP=$(cat <<EOF
Usage: $SELF [-M <mirror>] [-N <noproxy>] [-H <port>] [-S <port>] [-m <type>]
  [-n] [-h] [<host>] [<port>]
  Install Docker and configure it, e.g. proxy, mirror

  -M <mirror>:  registry mirror, default: $REPO_MIRROR
  -N <noproxy>: no_proxy settings, default: $PROXY_SKIP
  -H <port>:    proxy port for http, default: $PORT_HTTP
  -S <port>:    proxy port for https, default: $PORT_HTTPS
  -m <type>:    mirror option [$MIRRORS], default: $MIRROR
  -n:           dry run, print out information only, default: $DRY_RUN
  -h:           print the usage message

  <host>:       proxy host, "" to disable proxy, default: $PROXY_HOST
  <port>:       proxy port, override -HS options, default: $PROXY_PORT

Examples:

  1. Deploy with default configuration
     $SELF

  2. Deploy without proxy
     $SELF ""

  3. Deploy with specified proxy host and port (913 for http and https)
     $SELF http://proxy.example.com 913

  4. Deploy with specified proxy host and port (911 for http, 912 for https)
     $SELF -H 911 -S 912 http://proxy.example.com
EOF
)

while getopts ":N:M:H:S:m:nh" opt
do
  case $opt in
    M ) REPO_MIRROR=$OPTARG;;
    N ) PROXY_SKIP=$OPTARG;;
    H ) PORT_HTTP=$OPTARG;;
    S ) PORT_HTTPS=$OPTARG;;
    m ) MIRROR=$OPTARG
        if echo $MIRRORS | grep -v -w $MIRROR >/dev/null 2>&1; then
          echo "invalid mirror option $MIRROR"
          usage && exit 1
        fi
        ;;
    n ) DRY_RUN='y';;
    h ) echo "$HELP" && exit;;
    * ) echo "no such option: $opt" && exit 1;;
  esac
done
shift $((OPTIND-1))

if (( $# >= 1 )); then
  PROXY_HOST="$1"
fi
if (( $# >= 2 )); then
  PROXY_PORT="$2"
fi

SERVICE_CONFIG="/etc/systemd/system/docker.service.d/http-proxy.conf"
DOCKERD_CONFIG="/etc/docker/daemon.json"
DOCKERC_CONFIG="~/.docker/config.json"

DIST="$(source /etc/os-release && echo $ID | tr '[:upper:]' '[:lower:]')"

# export proxy settings
if [[ -n $PROXY_HOST ]]; then
  export http_proxy=$PROXY_HOST:${PROXY_PORT:-$PORT_HTTP}
  export https_proxy=$PROXY_HOST:${PROXY_PORT:-$PORT_HTTPS}
  export no_proxy=$PROXY_SKIP
else
  export http_proxy=
  export https_proxy=
  export no_proxy=
fi

for v in DRY_RUN DIST PROXY_HOST PROXY_PORT PROXY_SKIP PORT_HTTP PORT_HTTPS \
  MIRROR REPO_MIRROR SERVICE_CONFIG DOCKERD_CONFIG DOCKERC_CONFIG; do
  eval echo "$v: \${$v}"
done

[[ $DRY_RUN == "y" ]] && exit

echo "check prerequisites"
if [[ -z $(which curl) ]]; then
  echo "curl is not available"
  exit 1
fi
if [[ -z $(which python3) ]]; then
  echo "python3 is not available"
  exit 1
fi

# ensure Docker is installed
if [[ -z $(which docker) ]]; then
  echo "docker is not available, install it"
  if [[ $MIRROR == "auto" ]]; then
    MIRROR=yes # default as needed
    echo "check whether we can access google cloud"
    target="https://cloud.google.com"
    if curl -s -m 5 $target >/dev/null 2>&1; then
      echo "curl $target is OK"
      MIRROR=no
    else
      echo "curl $target is FAILED"
    fi
  fi

  echo "need mirror: $MIRROR"
  if [[ $DIST == "openeuler" ]]; then
    # WARN: only verified on openEuler 22.04 LTS
    # TODO: install latest version once openEuler has fuse-overlayfs
    repo_url="https://download.docker.com/linux/centos/docker-ce.repo"
    if [[ $MIRROR == "yes" ]]; then
      repo_url="https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo"
    fi
    $SUDO yum-config-manager --add-repo $repo_url
    echo "8" | $SUDO tee /etc/yum/vars/centosver
    $SUDO sed -i 's/\$releasever/\$centosver/g' /etc/yum.repos.d/docker-ce.repo
    $SUDO yum install -y docker-ce-19.03.15-3.el8
  else
    mirror_opt=""
    if [[ $MIRROR == "yes" ]]; then
      mirror_opt="--mirror Aliyun"
    fi
    curl -fsSL https://get.docker.com | bash -s docker $mirror_opt
  fi
  echo "docker installation is done"
fi

if [[ -e $SERVICE_CONFIG || -e $DOCKERD_CONFIG || -e $DOCKERC_CONFIG ]]; then
  cat <<EOF
any of the following configuration files already exist
* $SERVICE_CONFIG
* $DOCKERD_CONFIG
* $DOCKERC_CONFIG
EOF
  read -p "overwrite them and continue? y/N: " result
  if [[ $result != "y" ]]; then
    exit
  fi
fi

echo "configure docker client: $DOCKERC_CONFIG"
DOCKERC_CONFIG="$DOCKERC_CONFIG" python3 <<'EOF'
import os, json, pathlib, collections

nest_dict = lambda: collections.defaultdict(nest_dict)

f = pathlib.Path(os.environ['DOCKERC_CONFIG']).expanduser()
d = nest_dict()

try:
  with f.open() as fh:
    d.update(json.load(fh))
except FileNotFoundError:
  pass

m = dict(httpProxy='http_proxy', httpsProxy='https_proxy', noProxy='no_proxy')
d['proxies']['default'].update({ k : os.environ[v] for k, v in m.items() })

f.parent.mkdir(parents=True, exist_ok=True)
with f.open('w') as fh:
  json.dump(d, fh, indent=4)
EOF

echo "configure docker daemon"
echo "configure $SERVICE_CONFIG"
$SUDO mkdir -p $(dirname $SERVICE_CONFIG)
cat <<EOF | $SUDO tee $SERVICE_CONFIG
[Service]
Environment="HTTP_PROXY=$http_proxy"
Environment="HTTPS_PROXY=$https_proxy"
Environment="NO_PROXY=$no_proxy"
EOF

echo "configure $DOCKERD_CONFIG"
$SUDO mkdir -p $(dirname $DOCKERD_CONFIG)
mirrors=""
if [[ -n $REPO_MIRROR ]]; then
  mirrors="\"registry-mirrors\": [\"$REPO_MIRROR\"],"
fi
cat <<EOF | $SUDO tee $DOCKERD_CONFIG
{
  "log-opts": {
    "max-size": "500m"
  },
  $mirrors
  "exec-opts": ["native.cgroupdriver=systemd"],
  "insecure-registries": ["10.0.0.0/8", "127.0.0.0/8"]
}
EOF

echo "enable docker service"
$SUDO systemctl enable docker

echo "restart docker service"
$SUDO systemctl daemon-reload
$SUDO systemctl restart docker

if groups | grep -qwv docker; then
  echo "add docker group to $USER"
  $SUDO usermod -aG docker $USER
  echo "logout and login again or reboot to take effect"
fi
echo "done"
