#!/usr/bin/env bash
# author: joe.zheng
# version: 21.5.31

set -e

version="${1:-3.6.0}"
variant="linux-amd64"
name="helm-v$version-$variant"
file="$name.tar.gz"
cache="cache"

OS=$(uname | tr '[:upper:]' '[:lower:]')
if [[ $OS != "linux" ]]; then
  echo "only support linux"
  exit 1
fi

mkdir -p $cache
cd $cache

echo "download $file"
if [[ ! -e "$file" ]]; then
  curl -LO https://get.helm.sh/$file
fi

echo "install helm"
tar -zxf $file
sudo mv $variant/helm /usr/local/bin/helm
rm -rf $variant

echo "done, check version"
helm version