#!/usr/bin/env bash
# author: joe.zheng
# version: 24.03.29

set -e

SELF="$(basename $0)"
SELF_VERSION="$(sed -n '1,4s/# version: \(.*\)/\1/p' $0)"
NAME="${SELF#*-}"

SUDO="sudo"
if [[ $(id -u) == "0" ]]; then
  SUDO=""
fi

VERSION="3.14.2"      # version to install
CUR_VER=              # current version if any
DRY_RUN=n             # print information only
MIRROR="auto"         # mirror option
MIRRORS="yes no auto" # valid mirror options
UNINSTALL=n           # reset the deployment and uninstall components
OFFLINE=${OFFLINE:-n} # no external network

BASEURL="https://get.helm.sh"
BASEURL_MIRROR="https://mirrors.huaweicloud.com/helm"

VARIANT="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/')"
INSTALL_DIR_BIN="/usr/local/bin"

CACHE="cache"
CACHE_RUN="$CACHE/run/$SELF"
CACHE_PACKAGES="$CACHE/packages/common"
CACHE_DOWNLOADING="$CACHE/.download"

function msg() {
  echo "> $@"
}

function err() {
  echo "> $@" >&2
}

function usage() {
  cat <<EOF
Usage: $SELF [-m <type>] [-v <ver>] [-U] [-n] [-h]

  Setup Helm the easy way

  -m <type>: install via mirror [$MIRRORS], default: $MIRROR
  -v <ver>:  target version, default: $VERSION
  -U:        uninstall Helm, default: $UNINSTALL
  -n:        print information only, default: $DRY_RUN
  -h:        print the usage message

Cache:

  To speed up deployment, the required files will be cached at "$CACHE"

Examples:

  1. Install Helm
     $SELF

  2. Uninstall Helm
     $SELF -U

  3. Install Helm with specific version
     $SELF -v $VERSION

Version: $SELF_VERSION
EOF

}

function main() {
  # ensure the right one is used
  PATH=$INSTALL_DIR_BIN:$PATH

  # adjust default version if already deployed
  CUR_VER="$(current_version)"
  VERSION="${CUR_VER:-$VERSION}"

  while getopts ":m:v:hnU" opt
  do
    case $opt in
      m ) MIRROR=$OPTARG
          if echo $MIRRORS | grep -v -w $MIRROR >/dev/null 2>&1; then
            err "invalid mirror option $MIRROR"
            usage && exit 1
          fi
          ;;
      v ) VERSION=${OPTARG#v};;
      U ) UNINSTALL=y;;
      n ) DRY_RUN=y;;
      h ) usage && exit;;
      * ) usage && echo "invalid option: -$OPTARG" && exit 1;;
    esac
  done
  shift $((OPTIND-1))

  for v in CACHE DRY_RUN MIRROR UNINSTALL VERSION CUR_VER
  do
    eval echo "$v: \${$v}"
  done

  [[ $DRY_RUN == "y" ]] && exit

  validate_sudo
  check_prerequisites
  check_network
  check_mirror
  ensure_workdir

  local package_dir="$CACHE_PACKAGES/$NAME-$VERSION"
  local package_file="$NAME-v$VERSION-$VARIANT.tar.gz"

  mkdir -p $package_dir

  if [[ $OFFLINE == "y" ]]; then
    msg "WARNING: offline mode, cache must be ready"
  else
    local baseurl="$BASEURL"
    if [[ $USE_MIRROR = "y" ]]; then
      baseurl="$BASEURL_MIRROR/v$VERSION"
    fi
    download_file $baseurl/$package_file $package_dir/$package_file
  fi
  tar xzf $package_dir/$package_file -C $CACHE_RUN --strip-components=1

  if [[ $UNINSTALL == "y" ]]; then
    msg "uninstall $NAME"
    $SUDO rm -f $INSTALL_DIR_BIN/$NAME
  else
    msg "install $NAME"
    $SUDO install $CACHE_RUN/$NAME $INSTALL_DIR_BIN/$NAME

  cat <<EOF

# here are some tips to follow:
helm help
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo list
helm repo update
helm search repo bitnami
helm show chart bitnami/nginx
helm upgrade -i nginx bitnami/nginx
helm uninstall nginx
EOF
  fi

  echo "done"
}

function current_version() {
  local version=
  if [[ -n $(which $NAME) ]]; then
    version="$($NAME version --template '{{.Version}}')"
    version=${version#v}
  fi
  echo $version
}

function validate_sudo() {
  if [[ -n $SUDO ]]; then
    msg "validate sudo"
    sudo -v
  fi
}

function check_prerequisites() {
  msg "check prerequisites"
  if [[ -z $(which curl) ]]; then
    err "curl is not available"
    exit 1
  fi
  if ! kubectl version >/dev/null 2>&1; then
    err "can't access k8s cluster"
    msg "WARNING: $NAME will not work without k8s cluster!"
  fi
}

# the target URL is reachable but the response may be 4xx or 5xx
function can_access() {
   curl -IL -s -m 5 $1 >/dev/null 2>&1
}

function check_network() {
  msg "check network"
  if [[ $OFFLINE != 'y' ]]; then
    if ! curl -s -m 3 -I example.com >/dev/null; then
      msg "can't access external network"
      OFFLINE="y"
    fi
  fi
  msg "offline mode: $OFFLINE"
}

USE_MIRROR=n
function check_mirror() {
  msg "use mirror or not"
  if [[ $MIRROR == "auto" ]]; then
    MIRROR=yes # default as needed
    if [[ $OFFLINE == "y" ]]; then
      msg "offline mode, assume mirror is needed"
    else
      msg "check whether we can access $BASEURL"
      local target="$BASEURL"
      if can_access $target; then
        msg "curl $target is OK"
        MIRROR=no
      else
        msg "curl $target is FAILED"
      fi
    fi
  fi
  if [[ $MIRROR == "yes" ]]; then
    msg "mirror is needed"
    if can_access $BASEURL_MIRROR; then
      USE_MIRROR="y"
    else
      err "failed to access mirror ($BASEURL_MIRROR)"
    fi
  fi
  msg "use mirror: $USE_MIRROR"
}

function ensure_workdir() {
  msg "ensure workdir"

  for d in $CACHE_PACKAGES $CACHE_RUN $CACHE_DOWNLOADING; do
    if [[ ! -d $d ]]; then
      msg "create dir: $d"
      mkdir -p $d
    fi
  done
}

function download_file() {
  local src="${1:?missing source url}"
  local dst="${2:?missing destination}"

  if [[ -f "$dst" ]]; then
    msg "already exist: $dst"
  else
    msg "download: $src"
    local tmp="$CACHE_DOWNLOADING/$(basename $dst)"
    $RUN curl -fsSL $src > $tmp
    $RUN mkdir -p $(dirname $dst) && mv $tmp $dst
    msg "saved at: $dst"
  fi
}

main "$@"
