#!/usr/bin/env bash
# author: joe.zheng
# version: 23.10.22

set -e

SELF="$(basename $0)"
SELF_VERSION="$(sed -n '1,4s/# version: \(.*\)/\1/p' $0)"

SUDO="sudo"
if [[ $(id -u) == "0" ]]; then
  SUDO=""
fi

# details in https://istio.io/latest/docs/releases/supported-releases/
VERSION="1.17.8"      # version to install
DRY_RUN=n             # print information only
MIRROR="auto"         # mirror option
MIRRORS="yes no auto" # valid mirror options
UNINSTALL=n           # reset the deployment and uninstall components
OFFLINE=${OFFLINE:-n} # no external network

BASEURL="https://github.com/istio/istio"
MIRROR_URL="${MIRROR_URL:-https://ghps.cc}"
VARIANT="$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/')"

GCLOUD_TEST_URL="https://packages.cloud.google.com"        # google cloud url for test

CACHE="cache"
CACHE_PACKAGES="$CACHE/packages/common"

function msg() {
  echo "> $@"
}

function err() {
  echo "> $@" >&2
}

function usage() {
  cat <<EOF
Usage: $SELF [-m <type>] [-v <ver>] [-U] [-n] [-h]

  Setup Istio the easy way

  -m <type>: install via mirror [$MIRRORS], default: $MIRROR
  -v <ver>:  target version, default: $VERSION
  -U:        uninstall components, default: $UNINSTALL
  -n:        print information only, default: $DRY_RUN
  -h:        print the usage message

Cache:

  To speed up deployment, the required files will be cached at "$CACHE"

Environment variables:
  MIRROR_URL:  mirror to use, default: $MIRROR_URL
  OFFLINE:     force into offline mode [y n], default: $OFFLINE

Examples:

  1. Deploy Istio
     $SELF

  2. Install Istio with specific version
     $SELF -v 1.19.3

  3. Uninstall
     $SELF -U


Version: $SELF_VERSION
EOF

}

function main() {
  # adjust default version if already deployed
  local v="$(current_version)"
  VERSION="${v:-$VERSION}"

  while getopts ":m:v:hnU" opt
  do
    case $opt in
      m ) MIRROR=$OPTARG
          if echo $MIRRORS | grep -v -w $MIRROR >/dev/null 2>&1; then
            err "invalid mirror option $MIRROR"
            usage && exit 1
          fi
          ;;
      v ) VERSION=${OPTARG#v};;
      U ) UNINSTALL=y;;
      n ) DRY_RUN=y;;
      h ) usage && exit;;
      * ) usage && echo "invalid option: -$OPTARG" && exit 1;;
    esac
  done
  shift $((OPTIND-1))

  for v in CACHE DRY_RUN MIRROR UNINSTALL VERSION
  do
    eval echo "$v: \${$v}"
  done

  [[ $DRY_RUN == "y" ]] && exit

  validate_sudo
  check_prerequisites
  check_network
  check_mirror
  ensure_workdir

  local install_dir="/usr/local/bin"
  local install_bin="/usr/local/bin/istioctl"
  local package_dir="$CACHE_PACKAGES/istio-$VERSION"
  local package_bin="$package_dir/bin/istioctl"

  mkdir -p $package_dir

  if [[ ! -e "$package_bin" ]]; then
    if [[ $OFFLINE == "y" ]]; then
      msg "WARNING: offline mode, cache must be ready"
      msg "try to install from the cache"
    else
      local base_url="$BASEURL"
      local file="istio-$VERSION-$VARIANT.tar.gz"
      if [[ $NEED_MIRROR == "y" ]]; then
        base_url="$MIRROR_URL/$BASEURL"
      fi
      local package_url="$base_url/releases/download/$VERSION/$file"
      msg "download $package_url -> $package_dir"
      curl -L $package_url | tar xz -C $package_dir --strip-components=1
    fi
  fi

  if [[ $UNINSTALL == "y" ]]; then
    msg "uninstall istioctl"
    $SUDO rm -f $install_bin
  else
    msg "install istioctl"
    $SUDO install $package_bin $install_bin

    cat <<EOF
# here are some tips to follow:

# read https://istio.io/latest/docs/setup/getting-started
istioctl help
istioctl help profile
istioctl profile list

source <(istioctl completion bash)

istioctl install -y --set profile=demo
istioctl verify-install

kubectl label namespace default istio-injection=enabled
kubectl apply -f $package_dir/samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f $package_dir/samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl get po -w
istioctl analyze
kubectl get svc istio-ingressgateway -n istio-system

kubectl api-resources | grep istio
kubectl get gw -o yaml
kubectl get vs -o yaml

kubectl apply -f $package_dir/samples/addons
kubectl rollout status deployment/kiali -n istio-system
istioctl dashboard kiali

kubectl delete -f $package_dir/samples/addons
istioctl uninstall -y --purge
kubectl delete namespace istio-system
kubectl label namespace default istio-injection-
EOF

  fi

  msg "done"
}

function current_version() {
  local version=
  if [[ -n $(which istioctl) ]]; then
    version="$(istioctl version -s --remote=false)"
  fi
  echo $version
}

function validate_sudo() {
  if [[ -n $SUDO ]]; then
    msg "validate sudo"
    sudo -v
  fi
}

function check_prerequisites() {
  msg "check prerequisites"
  if [[ -z $(which curl) ]]; then
    err "curl is not available"
    exit 1
  fi
}

function check_network() {
  msg "check network"
  if [[ $OFFLINE != 'y' ]]; then
    if ! curl -s -m 3 -I example.com >/dev/null; then
      msg "can't access external network"
      OFFLINE="y"
    fi
  fi
  msg "offline mode: $OFFLINE"
}

NEED_MIRROR=n
function check_mirror() {
  msg "is mirror needed"
  if [[ $MIRROR == "auto" ]]; then
    MIRROR=yes # default as needed
    if [[ $OFFLINE == "y" ]]; then
      msg "offline mode, assume mirror is needed"
    else
      msg "check whether we can access google cloud"
      local target="$GCLOUD_TEST_URL"
      if curl -s -m 5 $target >/dev/null 2>&1; then
        msg "curl $target is OK"
        MIRROR=no
      else
        msg "curl $target is FAILED"
      fi
    fi
  fi
  if [[ $MIRROR == "yes" ]]; then
    NEED_MIRROR=y
  fi
  msg "need mirror: $NEED_MIRROR"
}

function ensure_workdir() {
  msg "ensure workdir"

  for d in $CACHE_PACKAGES; do
    if [[ ! -d $d ]]; then
      msg "create dir: $d"
      mkdir -p $d
    fi
  done
}

main "$@"
